// Currency data for currency selector with flags and symbols
// Common currencies first, then alphabetical by code

export interface Currency {
  code: string
  name: string
  flag: string
  symbol: string
}

export const CURRENCIES: Currency[] = [
  // Most common currencies first
  { code: "USD", name: "US Dollar", flag: "🇺🇸", symbol: "$" },
  { code: "EUR", name: "Euro", flag: "🇪🇺", symbol: "€" },
  { code: "GBP", name: "British Pound", flag: "🇬🇧", symbol: "£" },
  { code: "JPY", name: "Japanese Yen", flag: "🇯🇵", symbol: "¥" },
  { code: "CAD", name: "Canadian Dollar", flag: "🇨🇦", symbol: "$" },
  { code: "AUD", name: "Australian Dollar", flag: "🇦🇺", symbol: "$" },
  { code: "CHF", name: "Swiss Franc", flag: "🇨🇭", symbol: "CHF" },
  { code: "CNY", name: "Chinese Yuan", flag: "🇨🇳", symbol: "¥" },
  { code: "INR", name: "Indian Rupee", flag: "🇮🇳", symbol: "₹" },
  { code: "MXN", name: "Mexican Peso", flag: "🇲🇽", symbol: "$" },
  { code: "SGD", name: "Singapore Dollar", flag: "🇸🇬", symbol: "$" },
  { code: "HKD", name: "Hong Kong Dollar", flag: "🇭🇰", symbol: "$" },
  { code: "NZD", name: "New Zealand Dollar", flag: "🇳🇿", symbol: "$" },
  { code: "KRW", name: "South Korean Won", flag: "🇰🇷", symbol: "₩" },
  { code: "SEK", name: "Swedish Krona", flag: "🇸🇪", symbol: "kr" },
  { code: "NOK", name: "Norwegian Krone", flag: "🇳🇴", symbol: "kr" },
  { code: "DKK", name: "Danish Krone", flag: "🇩🇰", symbol: "kr" },
  { code: "THB", name: "Thai Baht", flag: "🇹🇭", symbol: "฿" },
  { code: "BRL", name: "Brazilian Real", flag: "🇧🇷", symbol: "R$" },
  { code: "ZAR", name: "South African Rand", flag: "🇿🇦", symbol: "R" },
  
  // Alphabetical from here
  { code: "AED", name: "UAE Dirham", flag: "🇦🇪", symbol: "د.إ" },
  { code: "AFN", name: "Afghan Afghani", flag: "🇦🇫", symbol: "؋" },
  { code: "ALL", name: "Albanian Lek", flag: "🇦🇱", symbol: "L" },
  { code: "AMD", name: "Armenian Dram", flag: "🇦🇲", symbol: "֏" },
  { code: "ANG", name: "Netherlands Antillean Guilder", flag: "🇨🇼", symbol: "ƒ" },
  { code: "AOA", name: "Angolan Kwanza", flag: "🇦🇴", symbol: "Kz" },
  { code: "ARS", name: "Argentine Peso", flag: "🇦🇷", symbol: "$" },
  { code: "AWG", name: "Aruban Florin", flag: "🇦🇼", symbol: "ƒ" },
  { code: "AZN", name: "Azerbaijani Manat", flag: "🇦🇿", symbol: "₼" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", flag: "🇧🇦", symbol: "KM" },
  { code: "BBD", name: "Barbadian Dollar", flag: "🇧🇧", symbol: "$" },
  { code: "BDT", name: "Bangladeshi Taka", flag: "🇧🇩", symbol: "৳" },
  { code: "BGN", name: "Bulgarian Lev", flag: "🇧🇬", symbol: "лв" },
  { code: "BHD", name: "Bahraini Dinar", flag: "🇧🇭", symbol: ".د.ب" },
  { code: "BIF", name: "Burundian Franc", flag: "🇧🇮", symbol: "FBu" },
  { code: "BMD", name: "Bermudian Dollar", flag: "🇧🇲", symbol: "$" },
  { code: "BND", name: "Brunei Dollar", flag: "🇧🇳", symbol: "$" },
  { code: "BOB", name: "Bolivian Boliviano", flag: "🇧🇴", symbol: "Bs." },
  { code: "BSD", name: "Bahamian Dollar", flag: "🇧🇸", symbol: "$" },
  { code: "BTN", name: "Bhutanese Ngultrum", flag: "🇧🇹", symbol: "Nu." },
  { code: "BWP", name: "Botswanan Pula", flag: "🇧🇼", symbol: "P" },
  { code: "BYN", name: "Belarusian Ruble", flag: "🇧🇾", symbol: "Br" },
  { code: "BZD", name: "Belize Dollar", flag: "🇧🇿", symbol: "$" },
  { code: "CDF", name: "Congolese Franc", flag: "🇨🇩", symbol: "FC" },
  { code: "CLP", name: "Chilean Peso", flag: "🇨🇱", symbol: "$" },
  { code: "COP", name: "Colombian Peso", flag: "🇨🇴", symbol: "$" },
  { code: "CRC", name: "Costa Rican Colón", flag: "🇨🇷", symbol: "₡" },
  { code: "CUP", name: "Cuban Peso", flag: "🇨🇺", symbol: "$" },
  { code: "CVE", name: "Cape Verdean Escudo", flag: "🇨🇻", symbol: "$" },
  { code: "CZK", name: "Czech Koruna", flag: "🇨🇿", symbol: "Kč" },
  { code: "DJF", name: "Djiboutian Franc", flag: "🇩🇯", symbol: "Fdj" },
  { code: "DOP", name: "Dominican Peso", flag: "🇩🇴", symbol: "$" },
  { code: "DZD", name: "Algerian Dinar", flag: "🇩🇿", symbol: "د.ج" },
  { code: "EGP", name: "Egyptian Pound", flag: "🇪🇬", symbol: "£" },
  { code: "ERN", name: "Eritrean Nakfa", flag: "🇪🇷", symbol: "Nfk" },
  { code: "ETB", name: "Ethiopian Birr", flag: "🇪🇹", symbol: "Br" },
  { code: "FJD", name: "Fijian Dollar", flag: "🇫🇯", symbol: "$" },
  { code: "FKP", name: "Falkland Islands Pound", flag: "🇫🇰", symbol: "£" },
  { code: "GEL", name: "Georgian Lari", flag: "🇬🇪", symbol: "₾" },
  { code: "GHS", name: "Ghanaian Cedi", flag: "🇬🇭", symbol: "₵" },
  { code: "GIP", name: "Gibraltar Pound", flag: "🇬🇮", symbol: "£" },
  { code: "GMD", name: "Gambian Dalasi", flag: "🇬🇲", symbol: "D" },
  { code: "GNF", name: "Guinean Franc", flag: "🇬🇳", symbol: "FG" },
  { code: "GTQ", name: "Guatemalan Quetzal", flag: "🇬🇹", symbol: "Q" },
  { code: "GYD", name: "Guyanese Dollar", flag: "🇬🇾", symbol: "$" },
  { code: "HNL", name: "Honduran Lempira", flag: "🇭🇳", symbol: "L" },
  { code: "HRK", name: "Croatian Kuna", flag: "🇭🇷", symbol: "kn" },
  { code: "HTG", name: "Haitian Gourde", flag: "🇭🇹", symbol: "G" },
  { code: "HUF", name: "Hungarian Forint", flag: "🇭🇺", symbol: "Ft" },
  { code: "IDR", name: "Indonesian Rupiah", flag: "🇮🇩", symbol: "Rp" },
  { code: "ILS", name: "Israeli New Shekel", flag: "🇮🇱", symbol: "₪" },
  { code: "IQD", name: "Iraqi Dinar", flag: "🇮🇶", symbol: "ع.د" },
  { code: "IRR", name: "Iranian Rial", flag: "🇮🇷", symbol: "﷼" },
  { code: "ISK", name: "Icelandic Króna", flag: "🇮🇸", symbol: "kr" },
  { code: "JMD", name: "Jamaican Dollar", flag: "🇯🇲", symbol: "$" },
  { code: "JOD", name: "Jordanian Dinar", flag: "🇯🇴", symbol: "د.ا" },
  { code: "KES", name: "Kenyan Shilling", flag: "🇰🇪", symbol: "KSh" },
  { code: "KGS", name: "Kyrgystani Som", flag: "🇰🇬", symbol: "с" },
  { code: "KHR", name: "Cambodian Riel", flag: "🇰🇭", symbol: "៛" },
  { code: "KMF", name: "Comorian Franc", flag: "🇰🇲", symbol: "CF" },
  { code: "KPW", name: "North Korean Won", flag: "🇰🇵", symbol: "₩" },
  { code: "KWD", name: "Kuwaiti Dinar", flag: "🇰🇼", symbol: "د.ك" },
  { code: "KYD", name: "Cayman Islands Dollar", flag: "🇰🇾", symbol: "$" },
  { code: "KZT", name: "Kazakhstani Tenge", flag: "🇰🇿", symbol: "₸" },
  { code: "LAK", name: "Laotian Kip", flag: "🇱🇦", symbol: "₭" },
  { code: "LBP", name: "Lebanese Pound", flag: "🇱🇧", symbol: "ل.ل" },
  { code: "LKR", name: "Sri Lankan Rupee", flag: "🇱🇰", symbol: "Rs" },
  { code: "LRD", name: "Liberian Dollar", flag: "🇱🇷", symbol: "$" },
  { code: "LSL", name: "Lesotho Loti", flag: "🇱🇸", symbol: "L" },
  { code: "LYD", name: "Libyan Dinar", flag: "🇱🇾", symbol: "ل.د" },
  { code: "MAD", name: "Moroccan Dirham", flag: "🇲🇦", symbol: "د.م." },
  { code: "MDL", name: "Moldovan Leu", flag: "🇲🇩", symbol: "L" },
  { code: "MGA", name: "Malagasy Ariary", flag: "🇲🇬", symbol: "Ar" },
  { code: "MKD", name: "Macedonian Denar", flag: "🇲🇰", symbol: "ден" },
  { code: "MMK", name: "Myanmar Kyat", flag: "🇲🇲", symbol: "K" },
  { code: "MNT", name: "Mongolian Tugrik", flag: "🇲🇳", symbol: "₮" },
  { code: "MOP", name: "Macanese Pataca", flag: "🇲🇴", symbol: "MOP$" },
  { code: "MRU", name: "Mauritanian Ouguiya", flag: "🇲🇷", symbol: "UM" },
  { code: "MUR", name: "Mauritian Rupee", flag: "🇲🇺", symbol: "₨" },
  { code: "MVR", name: "Maldivian Rufiyaa", flag: "🇲🇻", symbol: "Rf" },
  { code: "MWK", name: "Malawian Kwacha", flag: "🇲🇼", symbol: "MK" },
  { code: "MYR", name: "Malaysian Ringgit", flag: "🇲🇾", symbol: "RM" },
  { code: "MZN", name: "Mozambican Metical", flag: "🇲🇿", symbol: "MT" },
  { code: "NAD", name: "Namibian Dollar", flag: "🇳🇦", symbol: "$" },
  { code: "NGN", name: "Nigerian Naira", flag: "🇳🇬", symbol: "₦" },
  { code: "NIO", name: "Nicaraguan Córdoba", flag: "🇳🇮", symbol: "C$" },
  { code: "NPR", name: "Nepalese Rupee", flag: "🇳🇵", symbol: "₨" },
  { code: "OMR", name: "Omani Rial", flag: "🇴🇲", symbol: "ر.ع." },
  { code: "PAB", name: "Panamanian Balboa", flag: "🇵🇦", symbol: "B/." },
  { code: "PEN", name: "Peruvian Sol", flag: "🇵🇪", symbol: "S/" },
  { code: "PGK", name: "Papua New Guinean Kina", flag: "🇵🇬", symbol: "K" },
  { code: "PHP", name: "Philippine Peso", flag: "🇵🇭", symbol: "₱" },
  { code: "PKR", name: "Pakistani Rupee", flag: "🇵🇰", symbol: "₨" },
  { code: "PLN", name: "Polish Zloty", flag: "🇵🇱", symbol: "zł" },
  { code: "PYG", name: "Paraguayan Guarani", flag: "🇵🇾", symbol: "₲" },
  { code: "QAR", name: "Qatari Riyal", flag: "🇶🇦", symbol: "ر.ق" },
  { code: "RON", name: "Romanian Leu", flag: "🇷🇴", symbol: "lei" },
  { code: "RSD", name: "Serbian Dinar", flag: "🇷🇸", symbol: "дин." },
  { code: "RUB", name: "Russian Ruble", flag: "🇷🇺", symbol: "₽" },
  { code: "RWF", name: "Rwandan Franc", flag: "🇷🇼", symbol: "FRw" },
  { code: "SAR", name: "Saudi Riyal", flag: "🇸🇦", symbol: "ر.س" },
  { code: "SBD", name: "Solomon Islands Dollar", flag: "🇸🇧", symbol: "$" },
  { code: "SCR", name: "Seychellois Rupee", flag: "🇸🇨", symbol: "₨" },
  { code: "SDG", name: "Sudanese Pound", flag: "🇸🇩", symbol: "£" },
  { code: "SHP", name: "Saint Helena Pound", flag: "🇸🇭", symbol: "£" },
  { code: "SLL", name: "Sierra Leonean Leone", flag: "🇸🇱", symbol: "Le" },
  { code: "SOS", name: "Somali Shilling", flag: "🇸🇴", symbol: "S" },
  { code: "SRD", name: "Surinamese Dollar", flag: "🇸🇷", symbol: "$" },
  { code: "SSP", name: "South Sudanese Pound", flag: "🇸🇸", symbol: "£" },
  { code: "STN", name: "São Tomé and Príncipe Dobra", flag: "🇸🇹", symbol: "Db" },
  { code: "SYP", name: "Syrian Pound", flag: "🇸🇾", symbol: "£" },
  { code: "SZL", name: "Swazi Lilangeni", flag: "🇸🇿", symbol: "L" },
  { code: "TJS", name: "Tajikistani Somoni", flag: "🇹🇯", symbol: "ЅМ" },
  { code: "TMT", name: "Turkmenistani Manat", flag: "🇹🇲", symbol: "T" },
  { code: "TND", name: "Tunisian Dinar", flag: "🇹🇳", symbol: "د.ت" },
  { code: "TOP", name: "Tongan Paʻanga", flag: "🇹🇴", symbol: "T$" },
  { code: "TRY", name: "Turkish Lira", flag: "🇹🇷", symbol: "₺" },
  { code: "TTD", name: "Trinidad and Tobago Dollar", flag: "🇹🇹", symbol: "$" },
  { code: "TWD", name: "New Taiwan Dollar", flag: "🇹🇼", symbol: "NT$" },
  { code: "TZS", name: "Tanzanian Shilling", flag: "🇹🇿", symbol: "TSh" },
  { code: "UAH", name: "Ukrainian Hryvnia", flag: "🇺🇦", symbol: "₴" },
  { code: "UGX", name: "Ugandan Shilling", flag: "🇺🇬", symbol: "USh" },
  { code: "UYU", name: "Uruguayan Peso", flag: "🇺🇾", symbol: "$" },
  { code: "UZS", name: "Uzbekistani Som", flag: "🇺🇿", symbol: "сўм" },
  { code: "VES", name: "Venezuelan Bolívar", flag: "🇻🇪", symbol: "Bs." },
  { code: "VND", name: "Vietnamese Dong", flag: "🇻🇳", symbol: "₫" },
  { code: "VUV", name: "Vanuatu Vatu", flag: "🇻🇺", symbol: "VT" },
  { code: "WST", name: "Samoan Tala", flag: "🇼🇸", symbol: "T" },
  { code: "XAF", name: "Central African CFA Franc", flag: "🌍", symbol: "FCFA" },
  { code: "XCD", name: "East Caribbean Dollar", flag: "🌴", symbol: "$" },
  { code: "XOF", name: "West African CFA Franc", flag: "🌍", symbol: "CFA" },
  { code: "XPF", name: "CFP Franc", flag: "🌴", symbol: "₣" },
  { code: "YER", name: "Yemeni Rial", flag: "🇾🇪", symbol: "﷼" },
  { code: "ZMW", name: "Zambian Kwacha", flag: "🇿🇲", symbol: "ZK" },
  { code: "ZWL", name: "Zimbabwean Dollar", flag: "🇿🇼", symbol: "$" },
]

// Helper to get currency by code
export function getCurrencyByCode(code: string): Currency | undefined {
  return CURRENCIES.find(c => c.code.toUpperCase() === code.toUpperCase())
}

// Helper to format amount with currency symbol
export function formatCurrency(amount: number, currencyCode: string): string {
  const currency = getCurrencyByCode(currencyCode)
  if (!currency) {
    return `${amount.toFixed(2)} ${currencyCode}`
  }
  return `${currency.symbol}${amount.toFixed(2)}`
}

// Common currencies for quick selection
export const COMMON_CURRENCIES = CURRENCIES.slice(0, 20)
