"use client";

import { useState, useMemo } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { 
  ChevronDown, 
  ChevronRight,
  Heart,
  Plane,
  Sparkles,
  Users,
  DollarSign,
  Map as MapIcon,
  MapPin,
  MoreHorizontal,
  ArrowRight,
  Wand2,
  Globe,
  Lightbulb,
} from "lucide-react";
import { ProfileGraphItem, GraphCategory } from "@/lib/types/profile-graph";

interface SuggestionsClientProps {
  user: { id: string; name: string; email: string; image?: string };
  userProfile: {
    name: string;
    dateOfBirth: Date | null;
    city: string | null;
    country: string | null;
  };
  profileItems: ProfileGraphItem[];
  xmlData: string | null;
}

interface GroupedProfile {
  [category: string]: ProfileGraphItem[];
}

// Category configuration with icons and labels
const CATEGORY_CONFIG: Record<GraphCategory, { icon: any; label: string; color: string }> = {
  "travel-preferences": { icon: Plane, label: "Travel Preferences", color: "bg-blue-50 text-blue-700 border-blue-200" },
  "family": { icon: Users, label: "Family & Travel Companions", color: "bg-purple-50 text-purple-700 border-purple-200" },
  "hobbies": { icon: Heart, label: "Hobbies & Interests", color: "bg-pink-50 text-pink-700 border-pink-200" },
  "spending-priorities": { icon: DollarSign, label: "Spending Priorities", color: "bg-green-50 text-green-700 border-green-200" },
  "travel-style": { icon: MapPin, label: "Travel Style", color: "bg-orange-50 text-orange-700 border-orange-200" },
  "destinations": { icon: MapIcon, label: "Destinations", color: "bg-teal-50 text-teal-700 border-teal-200" },
  "other": { icon: MoreHorizontal, label: "Other", color: "bg-slate-50 text-slate-700 border-slate-200" },
};

// Journey option cards configuration
const JOURNEY_OPTIONS = [
  {
    id: "places",
    title: "Build Your Own",
    subtitle: "Places-Based Journey",
    description: "Pick your destinations using an interactive tile-based builder. Full control over your journey structure, dates, and stops.",
    icon: Globe,
    color: "from-emerald-500 to-teal-600",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
    href: "/suggestions/places",
    features: ["Choose multiple destinations", "Set duration for each stop", "Customize your route"],
  },
  {
    id: "wizard",
    title: "Guided Planning",
    subtitle: "5-Step Wizard",
    description: "Answer a few simple questions and let AI craft the perfect trip recommendation tailored to your preferences.",
    icon: Wand2,
    color: "from-violet-500 to-purple-600",
    bgColor: "bg-violet-50",
    borderColor: "border-violet-200",
    href: "/suggestions/wizard",
    features: ["When, Where, Budget, Who, What", "AI-powered recommendations", "Personalized to your profile"],
  },
  {
    id: "ideas",
    title: "Inspire Me",
    subtitle: "AI-Generated Ideas",
    description: "View 4 unique trip ideas generated by AI based on your travel profile. Perfect when you need inspiration.",
    icon: Lightbulb,
    color: "from-amber-500 to-orange-600",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
    href: "/suggestions/ideas",
    features: ["4 diverse trip options", "Based on your interests", "From local to multi-city"],
  },
];

export function SuggestionsClient({ user, userProfile, profileItems }: SuggestionsClientProps) {
  const [profileOpen, setProfileOpen] = useState(false);

  // Memoize grouped profile items by category
  const groupedProfile = useMemo<GroupedProfile>(() => {
    const seenIds = new Set<string>();
    const uniqueItems = profileItems.filter(item => {
      if (seenIds.has(item.id)) return false;
      seenIds.add(item.id);
      return true;
    });
    
    return uniqueItems.reduce((acc, item) => {
      const category = item.category || 'other';
      if (!acc[category]) {
        acc[category] = [];
      }
      acc[category].push(item);
      return acc;
    }, {} as GroupedProfile);
  }, [profileItems]);

  const totalItems = useMemo(() => profileItems.length, [profileItems]);

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-50 to-slate-100 pt-16">
      <div className="max-w-6xl mx-auto p-4 space-y-6">
        {/* Page Header */}
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold mb-3">Start a New Journey</h1>
          <p className="text-slate-600 text-lg max-w-2xl mx-auto">
            Choose how you&apos;d like to plan your next adventure. Each approach leads to a personalized trip recommendation.
          </p>
        </div>

        {/* Journey Option Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          {JOURNEY_OPTIONS.map((option, index) => {
            const Icon = option.icon;
            return (
              <motion.div
                key={option.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
              >
                <Card className={`h-full border-2 ${option.borderColor} hover:shadow-lg transition-all duration-300 group`}>
                  <CardHeader className="pb-3">
                    <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${option.color} flex items-center justify-center mb-3 group-hover:scale-110 transition-transform`}>
                      <Icon className="h-6 w-6 text-white" />
                    </div>
                    <CardTitle className="text-xl">{option.title}</CardTitle>
                    <CardDescription className="text-sm font-medium text-slate-500">
                      {option.subtitle}
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <p className="text-sm text-slate-600 leading-relaxed">
                      {option.description}
                    </p>
                    <ul className="space-y-1.5">
                      {option.features.map((feature, i) => (
                        <li key={i} className="text-xs text-slate-500 flex items-center gap-2">
                          <span className={`w-1.5 h-1.5 rounded-full bg-gradient-to-br ${option.color}`} />
                          {feature}
                        </li>
                      ))}
                    </ul>
                    <Link href={option.href} className="block">
                      <Button 
                        className={`w-full bg-gradient-to-r ${option.color} hover:opacity-90 transition-opacity`}
                      >
                        Get Started
                        <ArrowRight className="h-4 w-4 ml-2" />
                      </Button>
                    </Link>
                  </CardContent>
                </Card>
              </motion.div>
            );
          })}
        </div>

        {/* Profile Summary */}
        {profileItems.length > 0 ? (
          <Collapsible open={profileOpen} onOpenChange={setProfileOpen}>
            <Card className="border border-slate-200">
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between">
                  <CollapsibleTrigger className="flex items-center gap-3 flex-1 cursor-pointer hover:opacity-80 transition-opacity">
                    {profileOpen ? <ChevronDown className="h-5 w-5" /> : <ChevronRight className="h-5 w-5" />}
                    <div className="flex items-center gap-2">
                      <Sparkles className="h-5 w-5 text-purple-600" />
                      <CardTitle className="text-lg">Your Travel Profile</CardTitle>
                    </div>
                    <Badge variant="secondary" className="ml-2">
                      {totalItems} {totalItems === 1 ? 'item' : 'items'}
                    </Badge>
                  </CollapsibleTrigger>
                  <Link href="/profile#dossier">
                    <Button variant="ghost" size="sm" className="text-slate-500 hover:text-slate-700">
                      Edit Profile
                    </Button>
                  </Link>
                </div>
                <p className="text-sm text-slate-500 ml-8">
                  Your profile helps us personalize trip recommendations
                </p>
              </CardHeader>
              <CollapsibleContent>
                <CardContent className="pt-2">
                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
                    {Object.entries(groupedProfile).map(([category, items]) => {
                      const config = CATEGORY_CONFIG[category as GraphCategory] || CATEGORY_CONFIG.other;
                      const Icon = config.icon;
                      
                      return (
                        <Card key={category} className={`border ${config.color}`}>
                          <CardHeader className="pb-2">
                            <div className="flex items-center gap-2">
                              <Icon className="h-4 w-4" />
                              <CardTitle className="text-sm font-semibold">{config.label}</CardTitle>
                            </div>
                            <CardDescription className="text-xs">
                              {items.length} {items.length === 1 ? 'item' : 'items'}
                            </CardDescription>
                          </CardHeader>
                          <CardContent className="pt-0">
                            <div className="flex flex-wrap gap-1.5">
                              {items.slice(0, 6).map((item) => (
                                <Badge 
                                  key={item.id}
                                  variant="secondary" 
                                  className="text-xs font-normal"
                                >
                                  {item.value}
                                </Badge>
                              ))}
                              {items.length > 6 && (
                                <Badge variant="outline" className="text-xs">
                                  +{items.length - 6} more
                                </Badge>
                              )}
                            </div>
                          </CardContent>
                        </Card>
                      );
                    })}
                  </div>
                </CardContent>
              </CollapsibleContent>
            </Card>
          </Collapsible>
        ) : (
          <Card className="border border-amber-200 bg-amber-50">
            <CardHeader>
              <div className="flex items-center gap-2">
                <Sparkles className="h-5 w-5 text-amber-600" />
                <CardTitle className="text-lg">Build Your Travel Profile</CardTitle>
              </div>
              <CardDescription>
                Add your interests, preferences, and travel companions to get better recommendations
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-slate-600 mb-4">
                Your travel profile helps our AI understand your preferences and create personalized trip suggestions. 
                The more details you add, the better your recommendations will be.
              </p>
              <Link href="/profile#dossier">
                <Button variant="outline" className="border-amber-300 hover:bg-amber-100">
                  <Sparkles className="h-4 w-4 mr-2" />
                  Build Your Profile
                </Button>
              </Link>
            </CardContent>
          </Card>
        )}

        {/* How It Works Section */}
        <Card className="border border-slate-200 bg-white/50">
          <CardHeader>
            <CardTitle className="text-lg">How It Works</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-col md:flex-row items-start md:items-center gap-4 md:gap-8">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-full bg-slate-100 flex items-center justify-center text-sm font-semibold text-slate-600">1</div>
                <span className="text-sm text-slate-600">Choose your planning approach</span>
              </div>
              <ArrowRight className="h-4 w-4 text-slate-300 hidden md:block" />
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-full bg-slate-100 flex items-center justify-center text-sm font-semibold text-slate-600">2</div>
                <span className="text-sm text-slate-600">Complete the flow</span>
              </div>
              <ArrowRight className="h-4 w-4 text-slate-300 hidden md:block" />
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-full bg-slate-100 flex items-center justify-center text-sm font-semibold text-slate-600">3</div>
                <span className="text-sm text-slate-600">Review your trip recommendation</span>
              </div>
              <ArrowRight className="h-4 w-4 text-slate-300 hidden md:block" />
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-full bg-emerald-100 flex items-center justify-center text-sm font-semibold text-emerald-600">4</div>
                <span className="text-sm text-slate-600">Create and view your journey</span>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
